create table if not exists public.kategori (
  id_kategori integer generated by default as identity primary key,
  nama_kategori varchar(50) not null
);

create table if not exists public.merk (
  id_merk integer generated by default as identity primary key,
  nama_merk varchar(50) not null
);

create table if not exists public.produk (
  id_produk integer generated by default as identity primary key,
  id_kategori integer not null references public.kategori (id_kategori),
  id_merk integer not null references public.merk (id_merk),
  nama_produk varchar(100) not null,
  harga numeric(10, 2) not null,
  sae varchar(20) not null,
  volume varchar(20) not null,
  tipe varchar(50) not null,
  deskripsi text,
  gambar varchar(255)
);
